version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://user_tmdb:pass_tmdb@database:3306/tmdb_db?serverVersion=mariadb-10.9.4
      APP_SECRET: pass_tmdb
      MAILER_DSN: smtp://:@mailcatcher:1025
      MESSENGER_TRANSPORT_DSN: doctrine://default
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - database

  database:
    image: mariadb:10.9.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: tmdb_db
    ports:
      - "3306:3306"
    volumes:
      - tmdb_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database

  mailcatcher:
    image: schickling/mailcatcher
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  tmdb_db_data: